version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - php-network

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - php-network

networks:
  php-network:

volumes:
  mysql-data: